# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_AsmJit', [dirname(__file__)])
        except ImportError:
            import _AsmJit
            return _AsmJit
        if fp is not None:
            try:
                _mod = imp.load_module('_AsmJit', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _AsmJit = swig_import_helper()
    del swig_import_helper
else:
    import _AsmJit
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class uint8_tp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uint8_tp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uint8_tp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _AsmJit.new_uint8_tp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_uint8_tp
    __del__ = lambda self : None;
    def assign(self, *args): return _AsmJit.uint8_tp_assign(self, *args)
    def value(self): return _AsmJit.uint8_tp_value(self)
    def cast(self): return _AsmJit.uint8_tp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _AsmJit.uint8_tp_frompointer
    if _newclass:frompointer = staticmethod(_AsmJit.uint8_tp_frompointer)
uint8_tp_swigregister = _AsmJit.uint8_tp_swigregister
uint8_tp_swigregister(uint8_tp)

def uint8_tp_frompointer(*args):
  return _AsmJit.uint8_tp_frompointer(*args)
uint8_tp_frompointer = _AsmJit.uint8_tp_frompointer

class uint16_tp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uint16_tp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uint16_tp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _AsmJit.new_uint16_tp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_uint16_tp
    __del__ = lambda self : None;
    def assign(self, *args): return _AsmJit.uint16_tp_assign(self, *args)
    def value(self): return _AsmJit.uint16_tp_value(self)
    def cast(self): return _AsmJit.uint16_tp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _AsmJit.uint16_tp_frompointer
    if _newclass:frompointer = staticmethod(_AsmJit.uint16_tp_frompointer)
uint16_tp_swigregister = _AsmJit.uint16_tp_swigregister
uint16_tp_swigregister(uint16_tp)

def uint16_tp_frompointer(*args):
  return _AsmJit.uint16_tp_frompointer(*args)
uint16_tp_frompointer = _AsmJit.uint16_tp_frompointer

class uint32_tp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uint32_tp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uint32_tp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _AsmJit.new_uint32_tp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_uint32_tp
    __del__ = lambda self : None;
    def assign(self, *args): return _AsmJit.uint32_tp_assign(self, *args)
    def value(self): return _AsmJit.uint32_tp_value(self)
    def cast(self): return _AsmJit.uint32_tp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _AsmJit.uint32_tp_frompointer
    if _newclass:frompointer = staticmethod(_AsmJit.uint32_tp_frompointer)
uint32_tp_swigregister = _AsmJit.uint32_tp_swigregister
uint32_tp_swigregister(uint32_tp)

def uint32_tp_frompointer(*args):
  return _AsmJit.uint32_tp_frompointer(*args)
uint32_tp_frompointer = _AsmJit.uint32_tp_frompointer

class sysint_tp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, sysint_tp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, sysint_tp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _AsmJit.new_sysint_tp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_sysint_tp
    __del__ = lambda self : None;
    def assign(self, *args): return _AsmJit.sysint_tp_assign(self, *args)
    def value(self): return _AsmJit.sysint_tp_value(self)
    def cast(self): return _AsmJit.sysint_tp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _AsmJit.sysint_tp_frompointer
    if _newclass:frompointer = staticmethod(_AsmJit.sysint_tp_frompointer)
sysint_tp_swigregister = _AsmJit.sysint_tp_swigregister
sysint_tp_swigregister(sysint_tp)

def sysint_tp_frompointer(*args):
  return _AsmJit.sysint_tp_frompointer(*args)
sysint_tp_frompointer = _AsmJit.sysint_tp_frompointer


def _MemPtrAbs(*args):
  return _AsmJit._MemPtrAbs(*args)
_MemPtrAbs = _AsmJit._MemPtrAbs

def AbsPtr(*args):
  return _AsmJit.AbsPtr(*args)
AbsPtr = _AsmJit.AbsPtr
class FileLogger(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FileLogger, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FileLogger, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _AsmJit.new_FileLogger(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_FileLogger
    __del__ = lambda self : None;
FileLogger_swigregister = _AsmJit.FileLogger_swigregister
FileLogger_swigregister(FileLogger)

def ptr_abs(*args):
  return _AsmJit.ptr_abs(*args)
ptr_abs = _AsmJit.ptr_abs

class AssemblerCore(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AssemblerCore, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AssemblerCore, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _AsmJit.new_AssemblerCore(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_AssemblerCore
    __del__ = lambda self : None;
    def getCodeGenerator(self): return _AsmJit.AssemblerCore_getCodeGenerator(self)
    def getZone(self): return _AsmJit.AssemblerCore_getZone(self)
    def getLogger(self): return _AsmJit.AssemblerCore_getLogger(self)
    def setLogger(self, *args): return _AsmJit.AssemblerCore_setLogger(self, *args)
    def getError(self): return _AsmJit.AssemblerCore_getError(self)
    def setError(self, *args): return _AsmJit.AssemblerCore_setError(self, *args)
    def getProperty(self, *args): return _AsmJit.AssemblerCore_getProperty(self, *args)
    def setProperty(self, *args): return _AsmJit.AssemblerCore_setProperty(self, *args)
    def getCode(self): return _AsmJit.AssemblerCore_getCode(self)
    def ensureSpace(self): return _AsmJit.AssemblerCore_ensureSpace(self)
    def getOffset(self): return _AsmJit.AssemblerCore_getOffset(self)
    def getCodeSize(self): return _AsmJit.AssemblerCore_getCodeSize(self)
    def getTrampolineSize(self): return _AsmJit.AssemblerCore_getTrampolineSize(self)
    def toOffset(self, *args): return _AsmJit.AssemblerCore_toOffset(self, *args)
    def getCapacity(self): return _AsmJit.AssemblerCore_getCapacity(self)
    def clear(self): return _AsmJit.AssemblerCore_clear(self)
    def free(self): return _AsmJit.AssemblerCore_free(self)
    def takeCode(self): return _AsmJit.AssemblerCore_takeCode(self)
    def getByteAt(self, *args): return _AsmJit.AssemblerCore_getByteAt(self, *args)
    def getWordAt(self, *args): return _AsmJit.AssemblerCore_getWordAt(self, *args)
    def getDWordAt(self, *args): return _AsmJit.AssemblerCore_getDWordAt(self, *args)
    def getQWordAt(self, *args): return _AsmJit.AssemblerCore_getQWordAt(self, *args)
    def setByteAt(self, *args): return _AsmJit.AssemblerCore_setByteAt(self, *args)
    def setWordAt(self, *args): return _AsmJit.AssemblerCore_setWordAt(self, *args)
    def setDWordAt(self, *args): return _AsmJit.AssemblerCore_setDWordAt(self, *args)
    def setQWordAt(self, *args): return _AsmJit.AssemblerCore_setQWordAt(self, *args)
    def getInt32At(self, *args): return _AsmJit.AssemblerCore_getInt32At(self, *args)
    def setInt32At(self, *args): return _AsmJit.AssemblerCore_setInt32At(self, *args)
    def setVarAt(self, *args): return _AsmJit.AssemblerCore_setVarAt(self, *args)
    def canEmit(self): return _AsmJit.AssemblerCore_canEmit(self)
    def _emitByte(self, *args): return _AsmJit.AssemblerCore__emitByte(self, *args)
    def _emitWord(self, *args): return _AsmJit.AssemblerCore__emitWord(self, *args)
    def _emitDWord(self, *args): return _AsmJit.AssemblerCore__emitDWord(self, *args)
    def _emitQWord(self, *args): return _AsmJit.AssemblerCore__emitQWord(self, *args)
    def _emitInt32(self, *args): return _AsmJit.AssemblerCore__emitInt32(self, *args)
    def _emitSysInt(self, *args): return _AsmJit.AssemblerCore__emitSysInt(self, *args)
    def _emitSysUInt(self, *args): return _AsmJit.AssemblerCore__emitSysUInt(self, *args)
    def _emitOpCode(self, *args): return _AsmJit.AssemblerCore__emitOpCode(self, *args)
    def _emitSegmentPrefix(self, *args): return _AsmJit.AssemblerCore__emitSegmentPrefix(self, *args)
    def _emitMod(self, *args): return _AsmJit.AssemblerCore__emitMod(self, *args)
    def _emitSib(self, *args): return _AsmJit.AssemblerCore__emitSib(self, *args)
    def _emitRexR(self, *args): return _AsmJit.AssemblerCore__emitRexR(self, *args)
    def _emitRexRM(self, *args): return _AsmJit.AssemblerCore__emitRexRM(self, *args)
    def _emitModR(self, *args): return _AsmJit.AssemblerCore__emitModR(self, *args)
    def _emitModM(self, *args): return _AsmJit.AssemblerCore__emitModM(self, *args)
    def _emitModRM(self, *args): return _AsmJit.AssemblerCore__emitModRM(self, *args)
    def _emitX86Inl(self, *args): return _AsmJit.AssemblerCore__emitX86Inl(self, *args)
    def _emitX86RM(self, *args): return _AsmJit.AssemblerCore__emitX86RM(self, *args)
    def _emitFpu(self, *args): return _AsmJit.AssemblerCore__emitFpu(self, *args)
    def _emitFpuSTI(self, *args): return _AsmJit.AssemblerCore__emitFpuSTI(self, *args)
    def _emitFpuMEM(self, *args): return _AsmJit.AssemblerCore__emitFpuMEM(self, *args)
    def _emitMmu(self, *args): return _AsmJit.AssemblerCore__emitMmu(self, *args)
    def _emitJmpOrCallReloc(self, *args): return _AsmJit.AssemblerCore__emitJmpOrCallReloc(self, *args)
    def _emitInstruction(self, *args): return _AsmJit.AssemblerCore__emitInstruction(self, *args)
    def _emitJcc(self, *args): return _AsmJit.AssemblerCore__emitJcc(self, *args)
    def _emitShortJcc(self, *args): return _AsmJit.AssemblerCore__emitShortJcc(self, *args)
    def relocCode(self, *args): return _AsmJit.AssemblerCore_relocCode(self, *args)
    def embed(self, *args): return _AsmJit.AssemblerCore_embed(self, *args)
    def embedLabel(self, *args): return _AsmJit.AssemblerCore_embedLabel(self, *args)
    def align(self, *args): return _AsmJit.AssemblerCore_align(self, *args)
    def newLabel(self): return _AsmJit.AssemblerCore_newLabel(self)
    def registerLabels(self, *args): return _AsmJit.AssemblerCore_registerLabels(self, *args)
    def bind(self, *args): return _AsmJit.AssemblerCore_bind(self, *args)
    def make(self): return _AsmJit.AssemblerCore_make(self)
AssemblerCore_swigregister = _AsmJit.AssemblerCore_swigregister
AssemblerCore_swigregister(AssemblerCore)

class AssemblerIntrinsics(AssemblerCore):
    __swig_setmethods__ = {}
    for _s in [AssemblerCore]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AssemblerIntrinsics, name, value)
    __swig_getmethods__ = {}
    for _s in [AssemblerCore]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AssemblerIntrinsics, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _AsmJit.new_AssemblerIntrinsics(*args)
        try: self.this.append(this)
        except: self.this = this
    def db(self, *args): return _AsmJit.AssemblerIntrinsics_db(self, *args)
    def dw(self, *args): return _AsmJit.AssemblerIntrinsics_dw(self, *args)
    def dd(self, *args): return _AsmJit.AssemblerIntrinsics_dd(self, *args)
    def dq(self, *args): return _AsmJit.AssemblerIntrinsics_dq(self, *args)
    def dint8(self, *args): return _AsmJit.AssemblerIntrinsics_dint8(self, *args)
    def duint8(self, *args): return _AsmJit.AssemblerIntrinsics_duint8(self, *args)
    def dint16(self, *args): return _AsmJit.AssemblerIntrinsics_dint16(self, *args)
    def duint16(self, *args): return _AsmJit.AssemblerIntrinsics_duint16(self, *args)
    def dint32(self, *args): return _AsmJit.AssemblerIntrinsics_dint32(self, *args)
    def duint32(self, *args): return _AsmJit.AssemblerIntrinsics_duint32(self, *args)
    def dint64(self, *args): return _AsmJit.AssemblerIntrinsics_dint64(self, *args)
    def duint64(self, *args): return _AsmJit.AssemblerIntrinsics_duint64(self, *args)
    def dsysint(self, *args): return _AsmJit.AssemblerIntrinsics_dsysint(self, *args)
    def dsysuint(self, *args): return _AsmJit.AssemblerIntrinsics_dsysuint(self, *args)
    def dfloat(self, *args): return _AsmJit.AssemblerIntrinsics_dfloat(self, *args)
    def ddouble(self, *args): return _AsmJit.AssemblerIntrinsics_ddouble(self, *args)
    def dptr(self, *args): return _AsmJit.AssemblerIntrinsics_dptr(self, *args)
    def dmm(self, *args): return _AsmJit.AssemblerIntrinsics_dmm(self, *args)
    def dxmm(self, *args): return _AsmJit.AssemblerIntrinsics_dxmm(self, *args)
    def data(self, *args): return _AsmJit.AssemblerIntrinsics_data(self, *args)
    def adc(self, *args): return _AsmJit.AssemblerIntrinsics_adc(self, *args)
    def add(self, *args): return _AsmJit.AssemblerIntrinsics_add(self, *args)
    def and_(self, *args): return _AsmJit.AssemblerIntrinsics_and_(self, *args)
    def bsf(self, *args): return _AsmJit.AssemblerIntrinsics_bsf(self, *args)
    def bsr(self, *args): return _AsmJit.AssemblerIntrinsics_bsr(self, *args)
    def bswap(self, *args): return _AsmJit.AssemblerIntrinsics_bswap(self, *args)
    def bt(self, *args): return _AsmJit.AssemblerIntrinsics_bt(self, *args)
    def btc(self, *args): return _AsmJit.AssemblerIntrinsics_btc(self, *args)
    def btr(self, *args): return _AsmJit.AssemblerIntrinsics_btr(self, *args)
    def bts(self, *args): return _AsmJit.AssemblerIntrinsics_bts(self, *args)
    def call(self, *args): return _AsmJit.AssemblerIntrinsics_call(self, *args)
    def cbw(self): return _AsmJit.AssemblerIntrinsics_cbw(self)
    def cwde(self): return _AsmJit.AssemblerIntrinsics_cwde(self)
    def clc(self): return _AsmJit.AssemblerIntrinsics_clc(self)
    def cld(self): return _AsmJit.AssemblerIntrinsics_cld(self)
    def cmc(self): return _AsmJit.AssemblerIntrinsics_cmc(self)
    def cmov(self, *args): return _AsmJit.AssemblerIntrinsics_cmov(self, *args)
    def cmova(self, *args): return _AsmJit.AssemblerIntrinsics_cmova(self, *args)
    def cmovae(self, *args): return _AsmJit.AssemblerIntrinsics_cmovae(self, *args)
    def cmovb(self, *args): return _AsmJit.AssemblerIntrinsics_cmovb(self, *args)
    def cmovbe(self, *args): return _AsmJit.AssemblerIntrinsics_cmovbe(self, *args)
    def cmovc(self, *args): return _AsmJit.AssemblerIntrinsics_cmovc(self, *args)
    def cmove(self, *args): return _AsmJit.AssemblerIntrinsics_cmove(self, *args)
    def cmovg(self, *args): return _AsmJit.AssemblerIntrinsics_cmovg(self, *args)
    def cmovge(self, *args): return _AsmJit.AssemblerIntrinsics_cmovge(self, *args)
    def cmovl(self, *args): return _AsmJit.AssemblerIntrinsics_cmovl(self, *args)
    def cmovle(self, *args): return _AsmJit.AssemblerIntrinsics_cmovle(self, *args)
    def cmovna(self, *args): return _AsmJit.AssemblerIntrinsics_cmovna(self, *args)
    def cmovnae(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnae(self, *args)
    def cmovnb(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnb(self, *args)
    def cmovnbe(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnbe(self, *args)
    def cmovnc(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnc(self, *args)
    def cmovne(self, *args): return _AsmJit.AssemblerIntrinsics_cmovne(self, *args)
    def cmovng(self, *args): return _AsmJit.AssemblerIntrinsics_cmovng(self, *args)
    def cmovnge(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnge(self, *args)
    def cmovnl(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnl(self, *args)
    def cmovnle(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnle(self, *args)
    def cmovno(self, *args): return _AsmJit.AssemblerIntrinsics_cmovno(self, *args)
    def cmovnp(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnp(self, *args)
    def cmovns(self, *args): return _AsmJit.AssemblerIntrinsics_cmovns(self, *args)
    def cmovnz(self, *args): return _AsmJit.AssemblerIntrinsics_cmovnz(self, *args)
    def cmovo(self, *args): return _AsmJit.AssemblerIntrinsics_cmovo(self, *args)
    def cmovp(self, *args): return _AsmJit.AssemblerIntrinsics_cmovp(self, *args)
    def cmovpe(self, *args): return _AsmJit.AssemblerIntrinsics_cmovpe(self, *args)
    def cmovpo(self, *args): return _AsmJit.AssemblerIntrinsics_cmovpo(self, *args)
    def cmovs(self, *args): return _AsmJit.AssemblerIntrinsics_cmovs(self, *args)
    def cmovz(self, *args): return _AsmJit.AssemblerIntrinsics_cmovz(self, *args)
    def cmp(self, *args): return _AsmJit.AssemblerIntrinsics_cmp(self, *args)
    def cmpxchg(self, *args): return _AsmJit.AssemblerIntrinsics_cmpxchg(self, *args)
    def cmpxchg8b(self, *args): return _AsmJit.AssemblerIntrinsics_cmpxchg8b(self, *args)
    def cpuid(self): return _AsmJit.AssemblerIntrinsics_cpuid(self)
    def daa(self): return _AsmJit.AssemblerIntrinsics_daa(self)
    def das(self): return _AsmJit.AssemblerIntrinsics_das(self)
    def dec(self, *args): return _AsmJit.AssemblerIntrinsics_dec(self, *args)
    def div(self, *args): return _AsmJit.AssemblerIntrinsics_div(self, *args)
    def enter(self, *args): return _AsmJit.AssemblerIntrinsics_enter(self, *args)
    def idiv(self, *args): return _AsmJit.AssemblerIntrinsics_idiv(self, *args)
    def imul(self, *args): return _AsmJit.AssemblerIntrinsics_imul(self, *args)
    def inc(self, *args): return _AsmJit.AssemblerIntrinsics_inc(self, *args)
    def int3(self): return _AsmJit.AssemblerIntrinsics_int3(self)
    def j(self, *args): return _AsmJit.AssemblerIntrinsics_j(self, *args)
    def ja(self, *args): return _AsmJit.AssemblerIntrinsics_ja(self, *args)
    def jae(self, *args): return _AsmJit.AssemblerIntrinsics_jae(self, *args)
    def jb(self, *args): return _AsmJit.AssemblerIntrinsics_jb(self, *args)
    def jbe(self, *args): return _AsmJit.AssemblerIntrinsics_jbe(self, *args)
    def jc(self, *args): return _AsmJit.AssemblerIntrinsics_jc(self, *args)
    def je(self, *args): return _AsmJit.AssemblerIntrinsics_je(self, *args)
    def jg(self, *args): return _AsmJit.AssemblerIntrinsics_jg(self, *args)
    def jge(self, *args): return _AsmJit.AssemblerIntrinsics_jge(self, *args)
    def jl(self, *args): return _AsmJit.AssemblerIntrinsics_jl(self, *args)
    def jle(self, *args): return _AsmJit.AssemblerIntrinsics_jle(self, *args)
    def jna(self, *args): return _AsmJit.AssemblerIntrinsics_jna(self, *args)
    def jnae(self, *args): return _AsmJit.AssemblerIntrinsics_jnae(self, *args)
    def jnb(self, *args): return _AsmJit.AssemblerIntrinsics_jnb(self, *args)
    def jnbe(self, *args): return _AsmJit.AssemblerIntrinsics_jnbe(self, *args)
    def jnc(self, *args): return _AsmJit.AssemblerIntrinsics_jnc(self, *args)
    def jne(self, *args): return _AsmJit.AssemblerIntrinsics_jne(self, *args)
    def jng(self, *args): return _AsmJit.AssemblerIntrinsics_jng(self, *args)
    def jnge(self, *args): return _AsmJit.AssemblerIntrinsics_jnge(self, *args)
    def jnl(self, *args): return _AsmJit.AssemblerIntrinsics_jnl(self, *args)
    def jnle(self, *args): return _AsmJit.AssemblerIntrinsics_jnle(self, *args)
    def jno(self, *args): return _AsmJit.AssemblerIntrinsics_jno(self, *args)
    def jnp(self, *args): return _AsmJit.AssemblerIntrinsics_jnp(self, *args)
    def jns(self, *args): return _AsmJit.AssemblerIntrinsics_jns(self, *args)
    def jnz(self, *args): return _AsmJit.AssemblerIntrinsics_jnz(self, *args)
    def jo(self, *args): return _AsmJit.AssemblerIntrinsics_jo(self, *args)
    def jp(self, *args): return _AsmJit.AssemblerIntrinsics_jp(self, *args)
    def jpe(self, *args): return _AsmJit.AssemblerIntrinsics_jpe(self, *args)
    def jpo(self, *args): return _AsmJit.AssemblerIntrinsics_jpo(self, *args)
    def js(self, *args): return _AsmJit.AssemblerIntrinsics_js(self, *args)
    def jz(self, *args): return _AsmJit.AssemblerIntrinsics_jz(self, *args)
    def short_j(self, *args): return _AsmJit.AssemblerIntrinsics_short_j(self, *args)
    def short_ja(self, *args): return _AsmJit.AssemblerIntrinsics_short_ja(self, *args)
    def short_jae(self, *args): return _AsmJit.AssemblerIntrinsics_short_jae(self, *args)
    def short_jb(self, *args): return _AsmJit.AssemblerIntrinsics_short_jb(self, *args)
    def short_jbe(self, *args): return _AsmJit.AssemblerIntrinsics_short_jbe(self, *args)
    def short_jc(self, *args): return _AsmJit.AssemblerIntrinsics_short_jc(self, *args)
    def short_je(self, *args): return _AsmJit.AssemblerIntrinsics_short_je(self, *args)
    def short_jg(self, *args): return _AsmJit.AssemblerIntrinsics_short_jg(self, *args)
    def short_jge(self, *args): return _AsmJit.AssemblerIntrinsics_short_jge(self, *args)
    def short_jl(self, *args): return _AsmJit.AssemblerIntrinsics_short_jl(self, *args)
    def short_jle(self, *args): return _AsmJit.AssemblerIntrinsics_short_jle(self, *args)
    def short_jna(self, *args): return _AsmJit.AssemblerIntrinsics_short_jna(self, *args)
    def short_jnae(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnae(self, *args)
    def short_jnb(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnb(self, *args)
    def short_jnbe(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnbe(self, *args)
    def short_jnc(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnc(self, *args)
    def short_jne(self, *args): return _AsmJit.AssemblerIntrinsics_short_jne(self, *args)
    def short_jng(self, *args): return _AsmJit.AssemblerIntrinsics_short_jng(self, *args)
    def short_jnge(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnge(self, *args)
    def short_jnl(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnl(self, *args)
    def short_jnle(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnle(self, *args)
    def short_jno(self, *args): return _AsmJit.AssemblerIntrinsics_short_jno(self, *args)
    def short_jnp(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnp(self, *args)
    def short_jns(self, *args): return _AsmJit.AssemblerIntrinsics_short_jns(self, *args)
    def short_jnz(self, *args): return _AsmJit.AssemblerIntrinsics_short_jnz(self, *args)
    def short_jo(self, *args): return _AsmJit.AssemblerIntrinsics_short_jo(self, *args)
    def short_jp(self, *args): return _AsmJit.AssemblerIntrinsics_short_jp(self, *args)
    def short_jpe(self, *args): return _AsmJit.AssemblerIntrinsics_short_jpe(self, *args)
    def short_jpo(self, *args): return _AsmJit.AssemblerIntrinsics_short_jpo(self, *args)
    def short_js(self, *args): return _AsmJit.AssemblerIntrinsics_short_js(self, *args)
    def short_jz(self, *args): return _AsmJit.AssemblerIntrinsics_short_jz(self, *args)
    def jmp(self, *args): return _AsmJit.AssemblerIntrinsics_jmp(self, *args)
    def short_jmp(self, *args): return _AsmJit.AssemblerIntrinsics_short_jmp(self, *args)
    def lea(self, *args): return _AsmJit.AssemblerIntrinsics_lea(self, *args)
    def leave(self): return _AsmJit.AssemblerIntrinsics_leave(self)
    def mov(self, *args): return _AsmJit.AssemblerIntrinsics_mov(self, *args)
    def mov_ptr(self, *args): return _AsmJit.AssemblerIntrinsics_mov_ptr(self, *args)
    def movsx(self, *args): return _AsmJit.AssemblerIntrinsics_movsx(self, *args)
    def movzx(self, *args): return _AsmJit.AssemblerIntrinsics_movzx(self, *args)
    def mul(self, *args): return _AsmJit.AssemblerIntrinsics_mul(self, *args)
    def neg(self, *args): return _AsmJit.AssemblerIntrinsics_neg(self, *args)
    def nop(self): return _AsmJit.AssemblerIntrinsics_nop(self)
    def not_(self, *args): return _AsmJit.AssemblerIntrinsics_not_(self, *args)
    def or_(self, *args): return _AsmJit.AssemblerIntrinsics_or_(self, *args)
    def pop(self, *args): return _AsmJit.AssemblerIntrinsics_pop(self, *args)
    def popad(self): return _AsmJit.AssemblerIntrinsics_popad(self)
    def popf(self): return _AsmJit.AssemblerIntrinsics_popf(self)
    def popfd(self): return _AsmJit.AssemblerIntrinsics_popfd(self)
    def push(self, *args): return _AsmJit.AssemblerIntrinsics_push(self, *args)
    def pushad(self): return _AsmJit.AssemblerIntrinsics_pushad(self)
    def pushf(self): return _AsmJit.AssemblerIntrinsics_pushf(self)
    def pushfd(self): return _AsmJit.AssemblerIntrinsics_pushfd(self)
    def rcl(self, *args): return _AsmJit.AssemblerIntrinsics_rcl(self, *args)
    def rcr(self, *args): return _AsmJit.AssemblerIntrinsics_rcr(self, *args)
    def rdtsc(self): return _AsmJit.AssemblerIntrinsics_rdtsc(self)
    def rdtscp(self): return _AsmJit.AssemblerIntrinsics_rdtscp(self)
    def rep_lodsb(self): return _AsmJit.AssemblerIntrinsics_rep_lodsb(self)
    def rep_lodsd(self): return _AsmJit.AssemblerIntrinsics_rep_lodsd(self)
    def rep_lodsw(self): return _AsmJit.AssemblerIntrinsics_rep_lodsw(self)
    def rep_movsb(self): return _AsmJit.AssemblerIntrinsics_rep_movsb(self)
    def rep_movsd(self): return _AsmJit.AssemblerIntrinsics_rep_movsd(self)
    def rep_movsw(self): return _AsmJit.AssemblerIntrinsics_rep_movsw(self)
    def rep_stosb(self): return _AsmJit.AssemblerIntrinsics_rep_stosb(self)
    def rep_stosd(self): return _AsmJit.AssemblerIntrinsics_rep_stosd(self)
    def rep_stosw(self): return _AsmJit.AssemblerIntrinsics_rep_stosw(self)
    def repe_cmpsb(self): return _AsmJit.AssemblerIntrinsics_repe_cmpsb(self)
    def repe_cmpsd(self): return _AsmJit.AssemblerIntrinsics_repe_cmpsd(self)
    def repe_cmpsw(self): return _AsmJit.AssemblerIntrinsics_repe_cmpsw(self)
    def repe_scasb(self): return _AsmJit.AssemblerIntrinsics_repe_scasb(self)
    def repe_scasd(self): return _AsmJit.AssemblerIntrinsics_repe_scasd(self)
    def repe_scasw(self): return _AsmJit.AssemblerIntrinsics_repe_scasw(self)
    def repne_cmpsb(self): return _AsmJit.AssemblerIntrinsics_repne_cmpsb(self)
    def repne_cmpsd(self): return _AsmJit.AssemblerIntrinsics_repne_cmpsd(self)
    def repne_cmpsw(self): return _AsmJit.AssemblerIntrinsics_repne_cmpsw(self)
    def repne_scasb(self): return _AsmJit.AssemblerIntrinsics_repne_scasb(self)
    def repne_scasd(self): return _AsmJit.AssemblerIntrinsics_repne_scasd(self)
    def repne_scasw(self): return _AsmJit.AssemblerIntrinsics_repne_scasw(self)
    def ret(self, *args): return _AsmJit.AssemblerIntrinsics_ret(self, *args)
    def rol(self, *args): return _AsmJit.AssemblerIntrinsics_rol(self, *args)
    def ror(self, *args): return _AsmJit.AssemblerIntrinsics_ror(self, *args)
    def sahf(self): return _AsmJit.AssemblerIntrinsics_sahf(self)
    def sbb(self, *args): return _AsmJit.AssemblerIntrinsics_sbb(self, *args)
    def sal(self, *args): return _AsmJit.AssemblerIntrinsics_sal(self, *args)
    def sar(self, *args): return _AsmJit.AssemblerIntrinsics_sar(self, *args)
    def set(self, *args): return _AsmJit.AssemblerIntrinsics_set(self, *args)
    def seta(self, *args): return _AsmJit.AssemblerIntrinsics_seta(self, *args)
    def setae(self, *args): return _AsmJit.AssemblerIntrinsics_setae(self, *args)
    def setb(self, *args): return _AsmJit.AssemblerIntrinsics_setb(self, *args)
    def setbe(self, *args): return _AsmJit.AssemblerIntrinsics_setbe(self, *args)
    def setc(self, *args): return _AsmJit.AssemblerIntrinsics_setc(self, *args)
    def sete(self, *args): return _AsmJit.AssemblerIntrinsics_sete(self, *args)
    def setg(self, *args): return _AsmJit.AssemblerIntrinsics_setg(self, *args)
    def setge(self, *args): return _AsmJit.AssemblerIntrinsics_setge(self, *args)
    def setl(self, *args): return _AsmJit.AssemblerIntrinsics_setl(self, *args)
    def setle(self, *args): return _AsmJit.AssemblerIntrinsics_setle(self, *args)
    def setna(self, *args): return _AsmJit.AssemblerIntrinsics_setna(self, *args)
    def setnae(self, *args): return _AsmJit.AssemblerIntrinsics_setnae(self, *args)
    def setnb(self, *args): return _AsmJit.AssemblerIntrinsics_setnb(self, *args)
    def setnbe(self, *args): return _AsmJit.AssemblerIntrinsics_setnbe(self, *args)
    def setnc(self, *args): return _AsmJit.AssemblerIntrinsics_setnc(self, *args)
    def setne(self, *args): return _AsmJit.AssemblerIntrinsics_setne(self, *args)
    def setng(self, *args): return _AsmJit.AssemblerIntrinsics_setng(self, *args)
    def setnge(self, *args): return _AsmJit.AssemblerIntrinsics_setnge(self, *args)
    def setnl(self, *args): return _AsmJit.AssemblerIntrinsics_setnl(self, *args)
    def setnle(self, *args): return _AsmJit.AssemblerIntrinsics_setnle(self, *args)
    def setno(self, *args): return _AsmJit.AssemblerIntrinsics_setno(self, *args)
    def setnp(self, *args): return _AsmJit.AssemblerIntrinsics_setnp(self, *args)
    def setns(self, *args): return _AsmJit.AssemblerIntrinsics_setns(self, *args)
    def setnz(self, *args): return _AsmJit.AssemblerIntrinsics_setnz(self, *args)
    def seto(self, *args): return _AsmJit.AssemblerIntrinsics_seto(self, *args)
    def setp(self, *args): return _AsmJit.AssemblerIntrinsics_setp(self, *args)
    def setpe(self, *args): return _AsmJit.AssemblerIntrinsics_setpe(self, *args)
    def setpo(self, *args): return _AsmJit.AssemblerIntrinsics_setpo(self, *args)
    def sets(self, *args): return _AsmJit.AssemblerIntrinsics_sets(self, *args)
    def setz(self, *args): return _AsmJit.AssemblerIntrinsics_setz(self, *args)
    def shl(self, *args): return _AsmJit.AssemblerIntrinsics_shl(self, *args)
    def shr(self, *args): return _AsmJit.AssemblerIntrinsics_shr(self, *args)
    def shld(self, *args): return _AsmJit.AssemblerIntrinsics_shld(self, *args)
    def shrd(self, *args): return _AsmJit.AssemblerIntrinsics_shrd(self, *args)
    def stc(self): return _AsmJit.AssemblerIntrinsics_stc(self)
    def std(self): return _AsmJit.AssemblerIntrinsics_std(self)
    def sub(self, *args): return _AsmJit.AssemblerIntrinsics_sub(self, *args)
    def test(self, *args): return _AsmJit.AssemblerIntrinsics_test(self, *args)
    def ud2(self): return _AsmJit.AssemblerIntrinsics_ud2(self)
    def xadd(self, *args): return _AsmJit.AssemblerIntrinsics_xadd(self, *args)
    def xchg(self, *args): return _AsmJit.AssemblerIntrinsics_xchg(self, *args)
    def xor_(self, *args): return _AsmJit.AssemblerIntrinsics_xor_(self, *args)
    def f2xm1(self): return _AsmJit.AssemblerIntrinsics_f2xm1(self)
    def fabs(self): return _AsmJit.AssemblerIntrinsics_fabs(self)
    def fadd(self, *args): return _AsmJit.AssemblerIntrinsics_fadd(self, *args)
    def faddp(self, *args): return _AsmJit.AssemblerIntrinsics_faddp(self, *args)
    def fbld(self, *args): return _AsmJit.AssemblerIntrinsics_fbld(self, *args)
    def fbstp(self, *args): return _AsmJit.AssemblerIntrinsics_fbstp(self, *args)
    def fchs(self): return _AsmJit.AssemblerIntrinsics_fchs(self)
    def fclex(self): return _AsmJit.AssemblerIntrinsics_fclex(self)
    def fcmovb(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovb(self, *args)
    def fcmovbe(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovbe(self, *args)
    def fcmove(self, *args): return _AsmJit.AssemblerIntrinsics_fcmove(self, *args)
    def fcmovnb(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovnb(self, *args)
    def fcmovnbe(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovnbe(self, *args)
    def fcmovne(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovne(self, *args)
    def fcmovnu(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovnu(self, *args)
    def fcmovu(self, *args): return _AsmJit.AssemblerIntrinsics_fcmovu(self, *args)
    def fcom(self, *args): return _AsmJit.AssemblerIntrinsics_fcom(self, *args)
    def fcomp(self, *args): return _AsmJit.AssemblerIntrinsics_fcomp(self, *args)
    def fcompp(self): return _AsmJit.AssemblerIntrinsics_fcompp(self)
    def fcomi(self, *args): return _AsmJit.AssemblerIntrinsics_fcomi(self, *args)
    def fcomip(self, *args): return _AsmJit.AssemblerIntrinsics_fcomip(self, *args)
    def fcos(self): return _AsmJit.AssemblerIntrinsics_fcos(self)
    def fdecstp(self): return _AsmJit.AssemblerIntrinsics_fdecstp(self)
    def fdiv(self, *args): return _AsmJit.AssemblerIntrinsics_fdiv(self, *args)
    def fdivp(self, *args): return _AsmJit.AssemblerIntrinsics_fdivp(self, *args)
    def fdivr(self, *args): return _AsmJit.AssemblerIntrinsics_fdivr(self, *args)
    def fdivrp(self, *args): return _AsmJit.AssemblerIntrinsics_fdivrp(self, *args)
    def ffree(self, *args): return _AsmJit.AssemblerIntrinsics_ffree(self, *args)
    def fiadd(self, *args): return _AsmJit.AssemblerIntrinsics_fiadd(self, *args)
    def ficom(self, *args): return _AsmJit.AssemblerIntrinsics_ficom(self, *args)
    def ficomp(self, *args): return _AsmJit.AssemblerIntrinsics_ficomp(self, *args)
    def fidiv(self, *args): return _AsmJit.AssemblerIntrinsics_fidiv(self, *args)
    def fidivr(self, *args): return _AsmJit.AssemblerIntrinsics_fidivr(self, *args)
    def fild(self, *args): return _AsmJit.AssemblerIntrinsics_fild(self, *args)
    def fimul(self, *args): return _AsmJit.AssemblerIntrinsics_fimul(self, *args)
    def fincstp(self): return _AsmJit.AssemblerIntrinsics_fincstp(self)
    def finit(self): return _AsmJit.AssemblerIntrinsics_finit(self)
    def fisub(self, *args): return _AsmJit.AssemblerIntrinsics_fisub(self, *args)
    def fisubr(self, *args): return _AsmJit.AssemblerIntrinsics_fisubr(self, *args)
    def fninit(self): return _AsmJit.AssemblerIntrinsics_fninit(self)
    def fist(self, *args): return _AsmJit.AssemblerIntrinsics_fist(self, *args)
    def fistp(self, *args): return _AsmJit.AssemblerIntrinsics_fistp(self, *args)
    def fld(self, *args): return _AsmJit.AssemblerIntrinsics_fld(self, *args)
    def fld1(self): return _AsmJit.AssemblerIntrinsics_fld1(self)
    def fldl2t(self): return _AsmJit.AssemblerIntrinsics_fldl2t(self)
    def fldl2e(self): return _AsmJit.AssemblerIntrinsics_fldl2e(self)
    def fldpi(self): return _AsmJit.AssemblerIntrinsics_fldpi(self)
    def fldlg2(self): return _AsmJit.AssemblerIntrinsics_fldlg2(self)
    def fldln2(self): return _AsmJit.AssemblerIntrinsics_fldln2(self)
    def fldz(self): return _AsmJit.AssemblerIntrinsics_fldz(self)
    def fldcw(self, *args): return _AsmJit.AssemblerIntrinsics_fldcw(self, *args)
    def fldenv(self, *args): return _AsmJit.AssemblerIntrinsics_fldenv(self, *args)
    def fmul(self, *args): return _AsmJit.AssemblerIntrinsics_fmul(self, *args)
    def fmulp(self, *args): return _AsmJit.AssemblerIntrinsics_fmulp(self, *args)
    def fnclex(self): return _AsmJit.AssemblerIntrinsics_fnclex(self)
    def fnop(self): return _AsmJit.AssemblerIntrinsics_fnop(self)
    def fnsave(self, *args): return _AsmJit.AssemblerIntrinsics_fnsave(self, *args)
    def fnstenv(self, *args): return _AsmJit.AssemblerIntrinsics_fnstenv(self, *args)
    def fnstcw(self, *args): return _AsmJit.AssemblerIntrinsics_fnstcw(self, *args)
    def fnstsw(self, *args): return _AsmJit.AssemblerIntrinsics_fnstsw(self, *args)
    def fpatan(self): return _AsmJit.AssemblerIntrinsics_fpatan(self)
    def fprem(self): return _AsmJit.AssemblerIntrinsics_fprem(self)
    def fprem1(self): return _AsmJit.AssemblerIntrinsics_fprem1(self)
    def fptan(self): return _AsmJit.AssemblerIntrinsics_fptan(self)
    def frndint(self): return _AsmJit.AssemblerIntrinsics_frndint(self)
    def frstor(self, *args): return _AsmJit.AssemblerIntrinsics_frstor(self, *args)
    def fsave(self, *args): return _AsmJit.AssemblerIntrinsics_fsave(self, *args)
    def fscale(self): return _AsmJit.AssemblerIntrinsics_fscale(self)
    def fsin(self): return _AsmJit.AssemblerIntrinsics_fsin(self)
    def fsincos(self): return _AsmJit.AssemblerIntrinsics_fsincos(self)
    def fsqrt(self): return _AsmJit.AssemblerIntrinsics_fsqrt(self)
    def fst(self, *args): return _AsmJit.AssemblerIntrinsics_fst(self, *args)
    def fstp(self, *args): return _AsmJit.AssemblerIntrinsics_fstp(self, *args)
    def fstcw(self, *args): return _AsmJit.AssemblerIntrinsics_fstcw(self, *args)
    def fstenv(self, *args): return _AsmJit.AssemblerIntrinsics_fstenv(self, *args)
    def fstsw(self, *args): return _AsmJit.AssemblerIntrinsics_fstsw(self, *args)
    def fsub(self, *args): return _AsmJit.AssemblerIntrinsics_fsub(self, *args)
    def fsubp(self, *args): return _AsmJit.AssemblerIntrinsics_fsubp(self, *args)
    def fsubr(self, *args): return _AsmJit.AssemblerIntrinsics_fsubr(self, *args)
    def fsubrp(self, *args): return _AsmJit.AssemblerIntrinsics_fsubrp(self, *args)
    def ftst(self): return _AsmJit.AssemblerIntrinsics_ftst(self)
    def fucom(self, *args): return _AsmJit.AssemblerIntrinsics_fucom(self, *args)
    def fucomi(self, *args): return _AsmJit.AssemblerIntrinsics_fucomi(self, *args)
    def fucomip(self, *args): return _AsmJit.AssemblerIntrinsics_fucomip(self, *args)
    def fucomp(self, *args): return _AsmJit.AssemblerIntrinsics_fucomp(self, *args)
    def fucompp(self): return _AsmJit.AssemblerIntrinsics_fucompp(self)
    def fwait(self): return _AsmJit.AssemblerIntrinsics_fwait(self)
    def fxam(self): return _AsmJit.AssemblerIntrinsics_fxam(self)
    def fxch(self, *args): return _AsmJit.AssemblerIntrinsics_fxch(self, *args)
    def fxrstor(self, *args): return _AsmJit.AssemblerIntrinsics_fxrstor(self, *args)
    def fxsave(self, *args): return _AsmJit.AssemblerIntrinsics_fxsave(self, *args)
    def fxtract(self): return _AsmJit.AssemblerIntrinsics_fxtract(self)
    def fyl2x(self): return _AsmJit.AssemblerIntrinsics_fyl2x(self)
    def fyl2xp1(self): return _AsmJit.AssemblerIntrinsics_fyl2xp1(self)
    def emms(self): return _AsmJit.AssemblerIntrinsics_emms(self)
    def femms(self): return _AsmJit.AssemblerIntrinsics_femms(self)
    def pf2id(self, *args): return _AsmJit.AssemblerIntrinsics_pf2id(self, *args)
    def pf2iw(self, *args): return _AsmJit.AssemblerIntrinsics_pf2iw(self, *args)
    def pfacc(self, *args): return _AsmJit.AssemblerIntrinsics_pfacc(self, *args)
    def pfadd(self, *args): return _AsmJit.AssemblerIntrinsics_pfadd(self, *args)
    def pfcmpeq(self, *args): return _AsmJit.AssemblerIntrinsics_pfcmpeq(self, *args)
    def pfcmpge(self, *args): return _AsmJit.AssemblerIntrinsics_pfcmpge(self, *args)
    def pfcmpgt(self, *args): return _AsmJit.AssemblerIntrinsics_pfcmpgt(self, *args)
    def pfmax(self, *args): return _AsmJit.AssemblerIntrinsics_pfmax(self, *args)
    def pfmin(self, *args): return _AsmJit.AssemblerIntrinsics_pfmin(self, *args)
    def pfmul(self, *args): return _AsmJit.AssemblerIntrinsics_pfmul(self, *args)
    def pfnacc(self, *args): return _AsmJit.AssemblerIntrinsics_pfnacc(self, *args)
    def pfpnaxx(self, *args): return _AsmJit.AssemblerIntrinsics_pfpnaxx(self, *args)
    def pfpnacc(self, *args): return _AsmJit.AssemblerIntrinsics_pfpnacc(self, *args)
    def pfrcp(self, *args): return _AsmJit.AssemblerIntrinsics_pfrcp(self, *args)
    def pfrcpit1(self, *args): return _AsmJit.AssemblerIntrinsics_pfrcpit1(self, *args)
    def pfrcpit2(self, *args): return _AsmJit.AssemblerIntrinsics_pfrcpit2(self, *args)
    def pfrsqit1(self, *args): return _AsmJit.AssemblerIntrinsics_pfrsqit1(self, *args)
    def pfrsqrt(self, *args): return _AsmJit.AssemblerIntrinsics_pfrsqrt(self, *args)
    def pfsub(self, *args): return _AsmJit.AssemblerIntrinsics_pfsub(self, *args)
    def pfsubr(self, *args): return _AsmJit.AssemblerIntrinsics_pfsubr(self, *args)
    def pi2fd(self, *args): return _AsmJit.AssemblerIntrinsics_pi2fd(self, *args)
    def pi2fw(self, *args): return _AsmJit.AssemblerIntrinsics_pi2fw(self, *args)
    def pswapd(self, *args): return _AsmJit.AssemblerIntrinsics_pswapd(self, *args)
    def addps(self, *args): return _AsmJit.AssemblerIntrinsics_addps(self, *args)
    def addss(self, *args): return _AsmJit.AssemblerIntrinsics_addss(self, *args)
    def andnps(self, *args): return _AsmJit.AssemblerIntrinsics_andnps(self, *args)
    def andps(self, *args): return _AsmJit.AssemblerIntrinsics_andps(self, *args)
    def cmpps(self, *args): return _AsmJit.AssemblerIntrinsics_cmpps(self, *args)
    def cmpss(self, *args): return _AsmJit.AssemblerIntrinsics_cmpss(self, *args)
    def comiss(self, *args): return _AsmJit.AssemblerIntrinsics_comiss(self, *args)
    def cvtpi2ps(self, *args): return _AsmJit.AssemblerIntrinsics_cvtpi2ps(self, *args)
    def cvtps2pi(self, *args): return _AsmJit.AssemblerIntrinsics_cvtps2pi(self, *args)
    def cvtsi2ss(self, *args): return _AsmJit.AssemblerIntrinsics_cvtsi2ss(self, *args)
    def cvtss2si(self, *args): return _AsmJit.AssemblerIntrinsics_cvtss2si(self, *args)
    def cvttps2pi(self, *args): return _AsmJit.AssemblerIntrinsics_cvttps2pi(self, *args)
    def cvttss2si(self, *args): return _AsmJit.AssemblerIntrinsics_cvttss2si(self, *args)
    def divps(self, *args): return _AsmJit.AssemblerIntrinsics_divps(self, *args)
    def divss(self, *args): return _AsmJit.AssemblerIntrinsics_divss(self, *args)
    def ldmxcsr(self, *args): return _AsmJit.AssemblerIntrinsics_ldmxcsr(self, *args)
    def maskmovq(self, *args): return _AsmJit.AssemblerIntrinsics_maskmovq(self, *args)
    def maxps(self, *args): return _AsmJit.AssemblerIntrinsics_maxps(self, *args)
    def maxss(self, *args): return _AsmJit.AssemblerIntrinsics_maxss(self, *args)
    def minps(self, *args): return _AsmJit.AssemblerIntrinsics_minps(self, *args)
    def minss(self, *args): return _AsmJit.AssemblerIntrinsics_minss(self, *args)
    def movaps(self, *args): return _AsmJit.AssemblerIntrinsics_movaps(self, *args)
    def movd(self, *args): return _AsmJit.AssemblerIntrinsics_movd(self, *args)
    def movq(self, *args): return _AsmJit.AssemblerIntrinsics_movq(self, *args)
    def movntq(self, *args): return _AsmJit.AssemblerIntrinsics_movntq(self, *args)
    def movhlps(self, *args): return _AsmJit.AssemblerIntrinsics_movhlps(self, *args)
    def movhps(self, *args): return _AsmJit.AssemblerIntrinsics_movhps(self, *args)
    def movlhps(self, *args): return _AsmJit.AssemblerIntrinsics_movlhps(self, *args)
    def movlps(self, *args): return _AsmJit.AssemblerIntrinsics_movlps(self, *args)
    def movntps(self, *args): return _AsmJit.AssemblerIntrinsics_movntps(self, *args)
    def movss(self, *args): return _AsmJit.AssemblerIntrinsics_movss(self, *args)
    def movups(self, *args): return _AsmJit.AssemblerIntrinsics_movups(self, *args)
    def mulps(self, *args): return _AsmJit.AssemblerIntrinsics_mulps(self, *args)
    def mulss(self, *args): return _AsmJit.AssemblerIntrinsics_mulss(self, *args)
    def orps(self, *args): return _AsmJit.AssemblerIntrinsics_orps(self, *args)
    def pshufw(self, *args): return _AsmJit.AssemblerIntrinsics_pshufw(self, *args)
    def rcpps(self, *args): return _AsmJit.AssemblerIntrinsics_rcpps(self, *args)
    def rcpss(self, *args): return _AsmJit.AssemblerIntrinsics_rcpss(self, *args)
    def prefetch(self, *args): return _AsmJit.AssemblerIntrinsics_prefetch(self, *args)
    def psadbw(self, *args): return _AsmJit.AssemblerIntrinsics_psadbw(self, *args)
    def rsqrtps(self, *args): return _AsmJit.AssemblerIntrinsics_rsqrtps(self, *args)
    def rsqrtss(self, *args): return _AsmJit.AssemblerIntrinsics_rsqrtss(self, *args)
    def sfence(self): return _AsmJit.AssemblerIntrinsics_sfence(self)
    def shufps(self, *args): return _AsmJit.AssemblerIntrinsics_shufps(self, *args)
    def sqrtps(self, *args): return _AsmJit.AssemblerIntrinsics_sqrtps(self, *args)
    def sqrtss(self, *args): return _AsmJit.AssemblerIntrinsics_sqrtss(self, *args)
    def stmxcsr(self, *args): return _AsmJit.AssemblerIntrinsics_stmxcsr(self, *args)
    def subps(self, *args): return _AsmJit.AssemblerIntrinsics_subps(self, *args)
    def subss(self, *args): return _AsmJit.AssemblerIntrinsics_subss(self, *args)
    def ucomiss(self, *args): return _AsmJit.AssemblerIntrinsics_ucomiss(self, *args)
    def unpckhps(self, *args): return _AsmJit.AssemblerIntrinsics_unpckhps(self, *args)
    def unpcklps(self, *args): return _AsmJit.AssemblerIntrinsics_unpcklps(self, *args)
    def xorps(self, *args): return _AsmJit.AssemblerIntrinsics_xorps(self, *args)
    def addpd(self, *args): return _AsmJit.AssemblerIntrinsics_addpd(self, *args)
    def addsd(self, *args): return _AsmJit.AssemblerIntrinsics_addsd(self, *args)
    def andnpd(self, *args): return _AsmJit.AssemblerIntrinsics_andnpd(self, *args)
    def andpd(self, *args): return _AsmJit.AssemblerIntrinsics_andpd(self, *args)
    def clflush(self, *args): return _AsmJit.AssemblerIntrinsics_clflush(self, *args)
    def cmppd(self, *args): return _AsmJit.AssemblerIntrinsics_cmppd(self, *args)
    def cmpsd(self, *args): return _AsmJit.AssemblerIntrinsics_cmpsd(self, *args)
    def comisd(self, *args): return _AsmJit.AssemblerIntrinsics_comisd(self, *args)
    def cvtdq2pd(self, *args): return _AsmJit.AssemblerIntrinsics_cvtdq2pd(self, *args)
    def cvtdq2ps(self, *args): return _AsmJit.AssemblerIntrinsics_cvtdq2ps(self, *args)
    def cvtpd2dq(self, *args): return _AsmJit.AssemblerIntrinsics_cvtpd2dq(self, *args)
    def cvtpd2pi(self, *args): return _AsmJit.AssemblerIntrinsics_cvtpd2pi(self, *args)
    def cvtpd2ps(self, *args): return _AsmJit.AssemblerIntrinsics_cvtpd2ps(self, *args)
    def cvtpi2pd(self, *args): return _AsmJit.AssemblerIntrinsics_cvtpi2pd(self, *args)
    def cvtps2dq(self, *args): return _AsmJit.AssemblerIntrinsics_cvtps2dq(self, *args)
    def cvtps2pd(self, *args): return _AsmJit.AssemblerIntrinsics_cvtps2pd(self, *args)
    def cvtsd2si(self, *args): return _AsmJit.AssemblerIntrinsics_cvtsd2si(self, *args)
    def cvtsd2ss(self, *args): return _AsmJit.AssemblerIntrinsics_cvtsd2ss(self, *args)
    def cvtsi2sd(self, *args): return _AsmJit.AssemblerIntrinsics_cvtsi2sd(self, *args)
    def cvtss2sd(self, *args): return _AsmJit.AssemblerIntrinsics_cvtss2sd(self, *args)
    def cvttpd2pi(self, *args): return _AsmJit.AssemblerIntrinsics_cvttpd2pi(self, *args)
    def cvttpd2dq(self, *args): return _AsmJit.AssemblerIntrinsics_cvttpd2dq(self, *args)
    def cvttps2dq(self, *args): return _AsmJit.AssemblerIntrinsics_cvttps2dq(self, *args)
    def cvttsd2si(self, *args): return _AsmJit.AssemblerIntrinsics_cvttsd2si(self, *args)
    def divpd(self, *args): return _AsmJit.AssemblerIntrinsics_divpd(self, *args)
    def divsd(self, *args): return _AsmJit.AssemblerIntrinsics_divsd(self, *args)
    def lfence(self): return _AsmJit.AssemblerIntrinsics_lfence(self)
    def maskmovdqu(self, *args): return _AsmJit.AssemblerIntrinsics_maskmovdqu(self, *args)
    def maxpd(self, *args): return _AsmJit.AssemblerIntrinsics_maxpd(self, *args)
    def maxsd(self, *args): return _AsmJit.AssemblerIntrinsics_maxsd(self, *args)
    def mfence(self): return _AsmJit.AssemblerIntrinsics_mfence(self)
    def minpd(self, *args): return _AsmJit.AssemblerIntrinsics_minpd(self, *args)
    def minsd(self, *args): return _AsmJit.AssemblerIntrinsics_minsd(self, *args)
    def movdqa(self, *args): return _AsmJit.AssemblerIntrinsics_movdqa(self, *args)
    def movdqu(self, *args): return _AsmJit.AssemblerIntrinsics_movdqu(self, *args)
    def movmskps(self, *args): return _AsmJit.AssemblerIntrinsics_movmskps(self, *args)
    def movmskpd(self, *args): return _AsmJit.AssemblerIntrinsics_movmskpd(self, *args)
    def movsd(self, *args): return _AsmJit.AssemblerIntrinsics_movsd(self, *args)
    def movapd(self, *args): return _AsmJit.AssemblerIntrinsics_movapd(self, *args)
    def movdq2q(self, *args): return _AsmJit.AssemblerIntrinsics_movdq2q(self, *args)
    def movq2dq(self, *args): return _AsmJit.AssemblerIntrinsics_movq2dq(self, *args)
    def movhpd(self, *args): return _AsmJit.AssemblerIntrinsics_movhpd(self, *args)
    def movlpd(self, *args): return _AsmJit.AssemblerIntrinsics_movlpd(self, *args)
    def movntdq(self, *args): return _AsmJit.AssemblerIntrinsics_movntdq(self, *args)
    def movnti(self, *args): return _AsmJit.AssemblerIntrinsics_movnti(self, *args)
    def movntpd(self, *args): return _AsmJit.AssemblerIntrinsics_movntpd(self, *args)
    def movupd(self, *args): return _AsmJit.AssemblerIntrinsics_movupd(self, *args)
    def mulpd(self, *args): return _AsmJit.AssemblerIntrinsics_mulpd(self, *args)
    def mulsd(self, *args): return _AsmJit.AssemblerIntrinsics_mulsd(self, *args)
    def orpd(self, *args): return _AsmJit.AssemblerIntrinsics_orpd(self, *args)
    def packsswb(self, *args): return _AsmJit.AssemblerIntrinsics_packsswb(self, *args)
    def packssdw(self, *args): return _AsmJit.AssemblerIntrinsics_packssdw(self, *args)
    def packuswb(self, *args): return _AsmJit.AssemblerIntrinsics_packuswb(self, *args)
    def paddb(self, *args): return _AsmJit.AssemblerIntrinsics_paddb(self, *args)
    def paddw(self, *args): return _AsmJit.AssemblerIntrinsics_paddw(self, *args)
    def paddd(self, *args): return _AsmJit.AssemblerIntrinsics_paddd(self, *args)
    def paddq(self, *args): return _AsmJit.AssemblerIntrinsics_paddq(self, *args)
    def paddsb(self, *args): return _AsmJit.AssemblerIntrinsics_paddsb(self, *args)
    def paddsw(self, *args): return _AsmJit.AssemblerIntrinsics_paddsw(self, *args)
    def paddusb(self, *args): return _AsmJit.AssemblerIntrinsics_paddusb(self, *args)
    def paddusw(self, *args): return _AsmJit.AssemblerIntrinsics_paddusw(self, *args)
    def pand(self, *args): return _AsmJit.AssemblerIntrinsics_pand(self, *args)
    def pandn(self, *args): return _AsmJit.AssemblerIntrinsics_pandn(self, *args)
    def pause(self): return _AsmJit.AssemblerIntrinsics_pause(self)
    def pavgb(self, *args): return _AsmJit.AssemblerIntrinsics_pavgb(self, *args)
    def pavgw(self, *args): return _AsmJit.AssemblerIntrinsics_pavgw(self, *args)
    def pcmpeqb(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpeqb(self, *args)
    def pcmpeqw(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpeqw(self, *args)
    def pcmpeqd(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpeqd(self, *args)
    def pcmpgtb(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpgtb(self, *args)
    def pcmpgtw(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpgtw(self, *args)
    def pcmpgtd(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpgtd(self, *args)
    def pmaxsw(self, *args): return _AsmJit.AssemblerIntrinsics_pmaxsw(self, *args)
    def pmaxub(self, *args): return _AsmJit.AssemblerIntrinsics_pmaxub(self, *args)
    def pminsw(self, *args): return _AsmJit.AssemblerIntrinsics_pminsw(self, *args)
    def pminub(self, *args): return _AsmJit.AssemblerIntrinsics_pminub(self, *args)
    def pmovmskb(self, *args): return _AsmJit.AssemblerIntrinsics_pmovmskb(self, *args)
    def pmulhw(self, *args): return _AsmJit.AssemblerIntrinsics_pmulhw(self, *args)
    def pmulhuw(self, *args): return _AsmJit.AssemblerIntrinsics_pmulhuw(self, *args)
    def pmullw(self, *args): return _AsmJit.AssemblerIntrinsics_pmullw(self, *args)
    def pmuludq(self, *args): return _AsmJit.AssemblerIntrinsics_pmuludq(self, *args)
    def por(self, *args): return _AsmJit.AssemblerIntrinsics_por(self, *args)
    def pslld(self, *args): return _AsmJit.AssemblerIntrinsics_pslld(self, *args)
    def psllq(self, *args): return _AsmJit.AssemblerIntrinsics_psllq(self, *args)
    def psllw(self, *args): return _AsmJit.AssemblerIntrinsics_psllw(self, *args)
    def pslldq(self, *args): return _AsmJit.AssemblerIntrinsics_pslldq(self, *args)
    def psrad(self, *args): return _AsmJit.AssemblerIntrinsics_psrad(self, *args)
    def psraw(self, *args): return _AsmJit.AssemblerIntrinsics_psraw(self, *args)
    def psubb(self, *args): return _AsmJit.AssemblerIntrinsics_psubb(self, *args)
    def psubw(self, *args): return _AsmJit.AssemblerIntrinsics_psubw(self, *args)
    def psubd(self, *args): return _AsmJit.AssemblerIntrinsics_psubd(self, *args)
    def psubq(self, *args): return _AsmJit.AssemblerIntrinsics_psubq(self, *args)
    def pmaddwd(self, *args): return _AsmJit.AssemblerIntrinsics_pmaddwd(self, *args)
    def pshufd(self, *args): return _AsmJit.AssemblerIntrinsics_pshufd(self, *args)
    def pshufhw(self, *args): return _AsmJit.AssemblerIntrinsics_pshufhw(self, *args)
    def pshuflw(self, *args): return _AsmJit.AssemblerIntrinsics_pshuflw(self, *args)
    def psrld(self, *args): return _AsmJit.AssemblerIntrinsics_psrld(self, *args)
    def psrlq(self, *args): return _AsmJit.AssemblerIntrinsics_psrlq(self, *args)
    def psrldq(self, *args): return _AsmJit.AssemblerIntrinsics_psrldq(self, *args)
    def psrlw(self, *args): return _AsmJit.AssemblerIntrinsics_psrlw(self, *args)
    def psubsb(self, *args): return _AsmJit.AssemblerIntrinsics_psubsb(self, *args)
    def psubsw(self, *args): return _AsmJit.AssemblerIntrinsics_psubsw(self, *args)
    def psubusb(self, *args): return _AsmJit.AssemblerIntrinsics_psubusb(self, *args)
    def psubusw(self, *args): return _AsmJit.AssemblerIntrinsics_psubusw(self, *args)
    def punpckhbw(self, *args): return _AsmJit.AssemblerIntrinsics_punpckhbw(self, *args)
    def punpckhwd(self, *args): return _AsmJit.AssemblerIntrinsics_punpckhwd(self, *args)
    def punpckhdq(self, *args): return _AsmJit.AssemblerIntrinsics_punpckhdq(self, *args)
    def punpckhqdq(self, *args): return _AsmJit.AssemblerIntrinsics_punpckhqdq(self, *args)
    def punpcklbw(self, *args): return _AsmJit.AssemblerIntrinsics_punpcklbw(self, *args)
    def punpcklwd(self, *args): return _AsmJit.AssemblerIntrinsics_punpcklwd(self, *args)
    def punpckldq(self, *args): return _AsmJit.AssemblerIntrinsics_punpckldq(self, *args)
    def punpcklqdq(self, *args): return _AsmJit.AssemblerIntrinsics_punpcklqdq(self, *args)
    def pxor(self, *args): return _AsmJit.AssemblerIntrinsics_pxor(self, *args)
    def shufpd(self, *args): return _AsmJit.AssemblerIntrinsics_shufpd(self, *args)
    def sqrtpd(self, *args): return _AsmJit.AssemblerIntrinsics_sqrtpd(self, *args)
    def sqrtsd(self, *args): return _AsmJit.AssemblerIntrinsics_sqrtsd(self, *args)
    def subpd(self, *args): return _AsmJit.AssemblerIntrinsics_subpd(self, *args)
    def subsd(self, *args): return _AsmJit.AssemblerIntrinsics_subsd(self, *args)
    def ucomisd(self, *args): return _AsmJit.AssemblerIntrinsics_ucomisd(self, *args)
    def unpckhpd(self, *args): return _AsmJit.AssemblerIntrinsics_unpckhpd(self, *args)
    def unpcklpd(self, *args): return _AsmJit.AssemblerIntrinsics_unpcklpd(self, *args)
    def xorpd(self, *args): return _AsmJit.AssemblerIntrinsics_xorpd(self, *args)
    def addsubpd(self, *args): return _AsmJit.AssemblerIntrinsics_addsubpd(self, *args)
    def addsubps(self, *args): return _AsmJit.AssemblerIntrinsics_addsubps(self, *args)
    def fisttp(self, *args): return _AsmJit.AssemblerIntrinsics_fisttp(self, *args)
    def haddpd(self, *args): return _AsmJit.AssemblerIntrinsics_haddpd(self, *args)
    def haddps(self, *args): return _AsmJit.AssemblerIntrinsics_haddps(self, *args)
    def hsubpd(self, *args): return _AsmJit.AssemblerIntrinsics_hsubpd(self, *args)
    def hsubps(self, *args): return _AsmJit.AssemblerIntrinsics_hsubps(self, *args)
    def lddqu(self, *args): return _AsmJit.AssemblerIntrinsics_lddqu(self, *args)
    def monitor(self): return _AsmJit.AssemblerIntrinsics_monitor(self)
    def movddup(self, *args): return _AsmJit.AssemblerIntrinsics_movddup(self, *args)
    def movshdup(self, *args): return _AsmJit.AssemblerIntrinsics_movshdup(self, *args)
    def movsldup(self, *args): return _AsmJit.AssemblerIntrinsics_movsldup(self, *args)
    def mwait(self): return _AsmJit.AssemblerIntrinsics_mwait(self)
    def psignb(self, *args): return _AsmJit.AssemblerIntrinsics_psignb(self, *args)
    def psignw(self, *args): return _AsmJit.AssemblerIntrinsics_psignw(self, *args)
    def psignd(self, *args): return _AsmJit.AssemblerIntrinsics_psignd(self, *args)
    def phaddw(self, *args): return _AsmJit.AssemblerIntrinsics_phaddw(self, *args)
    def phaddd(self, *args): return _AsmJit.AssemblerIntrinsics_phaddd(self, *args)
    def phaddsw(self, *args): return _AsmJit.AssemblerIntrinsics_phaddsw(self, *args)
    def phsubw(self, *args): return _AsmJit.AssemblerIntrinsics_phsubw(self, *args)
    def phsubd(self, *args): return _AsmJit.AssemblerIntrinsics_phsubd(self, *args)
    def phsubsw(self, *args): return _AsmJit.AssemblerIntrinsics_phsubsw(self, *args)
    def pmaddubsw(self, *args): return _AsmJit.AssemblerIntrinsics_pmaddubsw(self, *args)
    def pabsb(self, *args): return _AsmJit.AssemblerIntrinsics_pabsb(self, *args)
    def pabsw(self, *args): return _AsmJit.AssemblerIntrinsics_pabsw(self, *args)
    def pabsd(self, *args): return _AsmJit.AssemblerIntrinsics_pabsd(self, *args)
    def pmulhrsw(self, *args): return _AsmJit.AssemblerIntrinsics_pmulhrsw(self, *args)
    def pshufb(self, *args): return _AsmJit.AssemblerIntrinsics_pshufb(self, *args)
    def palignr(self, *args): return _AsmJit.AssemblerIntrinsics_palignr(self, *args)
    def blendpd(self, *args): return _AsmJit.AssemblerIntrinsics_blendpd(self, *args)
    def blendps(self, *args): return _AsmJit.AssemblerIntrinsics_blendps(self, *args)
    def blendvpd(self, *args): return _AsmJit.AssemblerIntrinsics_blendvpd(self, *args)
    def blendvps(self, *args): return _AsmJit.AssemblerIntrinsics_blendvps(self, *args)
    def dppd(self, *args): return _AsmJit.AssemblerIntrinsics_dppd(self, *args)
    def dpps(self, *args): return _AsmJit.AssemblerIntrinsics_dpps(self, *args)
    def extractps(self, *args): return _AsmJit.AssemblerIntrinsics_extractps(self, *args)
    def movntdqa(self, *args): return _AsmJit.AssemblerIntrinsics_movntdqa(self, *args)
    def mpsadbw(self, *args): return _AsmJit.AssemblerIntrinsics_mpsadbw(self, *args)
    def packusdw(self, *args): return _AsmJit.AssemblerIntrinsics_packusdw(self, *args)
    def pblendvb(self, *args): return _AsmJit.AssemblerIntrinsics_pblendvb(self, *args)
    def pblendw(self, *args): return _AsmJit.AssemblerIntrinsics_pblendw(self, *args)
    def pcmpeqq(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpeqq(self, *args)
    def pextrb(self, *args): return _AsmJit.AssemblerIntrinsics_pextrb(self, *args)
    def pextrd(self, *args): return _AsmJit.AssemblerIntrinsics_pextrd(self, *args)
    def pextrq(self, *args): return _AsmJit.AssemblerIntrinsics_pextrq(self, *args)
    def pextrw(self, *args): return _AsmJit.AssemblerIntrinsics_pextrw(self, *args)
    def phminposuw(self, *args): return _AsmJit.AssemblerIntrinsics_phminposuw(self, *args)
    def pinsrb(self, *args): return _AsmJit.AssemblerIntrinsics_pinsrb(self, *args)
    def pinsrd(self, *args): return _AsmJit.AssemblerIntrinsics_pinsrd(self, *args)
    def pinsrq(self, *args): return _AsmJit.AssemblerIntrinsics_pinsrq(self, *args)
    def pinsrw(self, *args): return _AsmJit.AssemblerIntrinsics_pinsrw(self, *args)
    def pmaxuw(self, *args): return _AsmJit.AssemblerIntrinsics_pmaxuw(self, *args)
    def pmaxsb(self, *args): return _AsmJit.AssemblerIntrinsics_pmaxsb(self, *args)
    def pmaxsd(self, *args): return _AsmJit.AssemblerIntrinsics_pmaxsd(self, *args)
    def pmaxud(self, *args): return _AsmJit.AssemblerIntrinsics_pmaxud(self, *args)
    def pminsb(self, *args): return _AsmJit.AssemblerIntrinsics_pminsb(self, *args)
    def pminuw(self, *args): return _AsmJit.AssemblerIntrinsics_pminuw(self, *args)
    def pminud(self, *args): return _AsmJit.AssemblerIntrinsics_pminud(self, *args)
    def pminsd(self, *args): return _AsmJit.AssemblerIntrinsics_pminsd(self, *args)
    def pmovsxbw(self, *args): return _AsmJit.AssemblerIntrinsics_pmovsxbw(self, *args)
    def pmovsxbd(self, *args): return _AsmJit.AssemblerIntrinsics_pmovsxbd(self, *args)
    def pmovsxbq(self, *args): return _AsmJit.AssemblerIntrinsics_pmovsxbq(self, *args)
    def pmovsxwd(self, *args): return _AsmJit.AssemblerIntrinsics_pmovsxwd(self, *args)
    def pmovsxwq(self, *args): return _AsmJit.AssemblerIntrinsics_pmovsxwq(self, *args)
    def pmovsxdq(self, *args): return _AsmJit.AssemblerIntrinsics_pmovsxdq(self, *args)
    def pmovzxbw(self, *args): return _AsmJit.AssemblerIntrinsics_pmovzxbw(self, *args)
    def pmovzxbd(self, *args): return _AsmJit.AssemblerIntrinsics_pmovzxbd(self, *args)
    def pmovzxbq(self, *args): return _AsmJit.AssemblerIntrinsics_pmovzxbq(self, *args)
    def pmovzxwd(self, *args): return _AsmJit.AssemblerIntrinsics_pmovzxwd(self, *args)
    def pmovzxwq(self, *args): return _AsmJit.AssemblerIntrinsics_pmovzxwq(self, *args)
    def pmovzxdq(self, *args): return _AsmJit.AssemblerIntrinsics_pmovzxdq(self, *args)
    def pmuldq(self, *args): return _AsmJit.AssemblerIntrinsics_pmuldq(self, *args)
    def pmulld(self, *args): return _AsmJit.AssemblerIntrinsics_pmulld(self, *args)
    def ptest(self, *args): return _AsmJit.AssemblerIntrinsics_ptest(self, *args)
    def roundps(self, *args): return _AsmJit.AssemblerIntrinsics_roundps(self, *args)
    def roundss(self, *args): return _AsmJit.AssemblerIntrinsics_roundss(self, *args)
    def roundpd(self, *args): return _AsmJit.AssemblerIntrinsics_roundpd(self, *args)
    def roundsd(self, *args): return _AsmJit.AssemblerIntrinsics_roundsd(self, *args)
    def crc32(self, *args): return _AsmJit.AssemblerIntrinsics_crc32(self, *args)
    def pcmpestri(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpestri(self, *args)
    def pcmpestrm(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpestrm(self, *args)
    def pcmpistri(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpistri(self, *args)
    def pcmpistrm(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpistrm(self, *args)
    def pcmpgtq(self, *args): return _AsmJit.AssemblerIntrinsics_pcmpgtq(self, *args)
    def popcnt(self, *args): return _AsmJit.AssemblerIntrinsics_popcnt(self, *args)
    def amd_prefetch(self, *args): return _AsmJit.AssemblerIntrinsics_amd_prefetch(self, *args)
    def amd_prefetchw(self, *args): return _AsmJit.AssemblerIntrinsics_amd_prefetchw(self, *args)
    def movbe(self, *args): return _AsmJit.AssemblerIntrinsics_movbe(self, *args)
    def lock(self): return _AsmJit.AssemblerIntrinsics_lock(self)
    def rex(self): return _AsmJit.AssemblerIntrinsics_rex(self)
    __swig_destroy__ = _AsmJit.delete_AssemblerIntrinsics
    __del__ = lambda self : None;
AssemblerIntrinsics_swigregister = _AsmJit.AssemblerIntrinsics_swigregister
AssemblerIntrinsics_swigregister(AssemblerIntrinsics)

class Assembler(AssemblerIntrinsics):
    __swig_setmethods__ = {}
    for _s in [AssemblerIntrinsics]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Assembler, name, value)
    __swig_getmethods__ = {}
    for _s in [AssemblerIntrinsics]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Assembler, name)
    __repr__ = _swig_repr
    def __init__(self, codeGenerator = None): 
        this = _AsmJit.new_Assembler(codeGenerator)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _AsmJit.delete_Assembler
    __del__ = lambda self : None;
Assembler_swigregister = _AsmJit.Assembler_swigregister
Assembler_swigregister(Assembler)


cvar = _AsmJit.cvar
no_reg = cvar.no_reg
al = cvar.al
cl = cvar.cl
dl = cvar.dl
bl = cvar.bl
ah = cvar.ah
ch = cvar.ch
dh = cvar.dh
bh = cvar.bh
ax = cvar.ax
cx = cvar.cx
dx = cvar.dx
bx = cvar.bx
sp = cvar.sp
bp = cvar.bp
si = cvar.si
di = cvar.di
eax = cvar.eax
ecx = cvar.ecx
edx = cvar.edx
ebx = cvar.ebx
esp = cvar.esp
ebp = cvar.ebp
esi = cvar.esi
edi = cvar.edi
nax = cvar.nax
ncx = cvar.ncx
ndx = cvar.ndx
nbx = cvar.nbx
nsp = cvar.nsp
nbp = cvar.nbp
nsi = cvar.nsi
ndi = cvar.ndi
mm0 = cvar.mm0
mm1 = cvar.mm1
mm2 = cvar.mm2
mm3 = cvar.mm3
mm4 = cvar.mm4
mm5 = cvar.mm5
mm6 = cvar.mm6
mm7 = cvar.mm7
xmm0 = cvar.xmm0
xmm1 = cvar.xmm1
xmm2 = cvar.xmm2
xmm3 = cvar.xmm3
xmm4 = cvar.xmm4
xmm5 = cvar.xmm5
xmm6 = cvar.xmm6
xmm7 = cvar.xmm7
cs = cvar.cs
ss = cvar.ss
ds = cvar.ds
es = cvar.es
fs = cvar.fs
gs = cvar.gs

