# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rudd/dev/asmjit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rudd/dev/asmjit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rudd/dev/asmjit/CMakeFiles /home/rudd/dev/asmjit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rudd/dev/asmjit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _AsmJit

# Build rule for target.
_AsmJit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _AsmJit
.PHONY : _AsmJit

# fast build rule for target.
_AsmJit/fast:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/build
.PHONY : _AsmJit/fast

deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.o: deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.i: deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.s: deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.o: deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.i: deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.s: deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/Compiler.o: deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Compiler.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/Compiler.i: deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Compiler.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/Compiler.s: deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Compiler.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Compiler.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.o: deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.i: deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.s: deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.o: deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.i: deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.s: deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/Defs.o: deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Defs.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/Defs.i: deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Defs.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/Defs.s: deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Defs.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Defs.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.o: deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.i: deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.s: deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/Logger.o: deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Logger.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/Logger.i: deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Logger.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/Logger.s: deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Logger.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Logger.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.o: deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.i: deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.s: deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.o: deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.i: deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.s: deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.o: deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.i: deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.s: deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/Platform.o: deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Platform.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/Platform.i: deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Platform.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/Platform.s: deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Platform.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Platform.cpp.s

deps/AsmJit-1.0-beta4/AsmJit/Util.o: deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Util.o

# target to build an object file
deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.o
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.o

deps/AsmJit-1.0-beta4/AsmJit/Util.i: deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Util.i

# target to preprocess a source file
deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.i
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.i

deps/AsmJit-1.0-beta4/AsmJit/Util.s: deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Util.s

# target to generate assembly for a file
deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.s
.PHONY : deps/AsmJit-1.0-beta4/AsmJit/Util.cpp.s

swig/AsmJitPYTHON_wrap.o: swig/AsmJitPYTHON_wrap.cxx.o
.PHONY : swig/AsmJitPYTHON_wrap.o

# target to build an object file
swig/AsmJitPYTHON_wrap.cxx.o:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/swig/AsmJitPYTHON_wrap.cxx.o
.PHONY : swig/AsmJitPYTHON_wrap.cxx.o

swig/AsmJitPYTHON_wrap.i: swig/AsmJitPYTHON_wrap.cxx.i
.PHONY : swig/AsmJitPYTHON_wrap.i

# target to preprocess a source file
swig/AsmJitPYTHON_wrap.cxx.i:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/swig/AsmJitPYTHON_wrap.cxx.i
.PHONY : swig/AsmJitPYTHON_wrap.cxx.i

swig/AsmJitPYTHON_wrap.s: swig/AsmJitPYTHON_wrap.cxx.s
.PHONY : swig/AsmJitPYTHON_wrap.s

# target to generate assembly for a file
swig/AsmJitPYTHON_wrap.cxx.s:
	$(MAKE) -f CMakeFiles/_AsmJit.dir/build.make CMakeFiles/_AsmJit.dir/swig/AsmJitPYTHON_wrap.cxx.s
.PHONY : swig/AsmJitPYTHON_wrap.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... _AsmJit"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/AssemblerX86X64.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CodeGenerator.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Compiler.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Compiler.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Compiler.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CompilerX86X64.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/CpuInfo.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Defs.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Defs.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Defs.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/DefsX86X64.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Logger.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Logger.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Logger.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/MemoryManager.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/MemoryMarker.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/OperandX86X64.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Platform.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Platform.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Platform.s"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Util.o"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Util.i"
	@echo "... deps/AsmJit-1.0-beta4/AsmJit/Util.s"
	@echo "... swig/AsmJitPYTHON_wrap.o"
	@echo "... swig/AsmJitPYTHON_wrap.i"
	@echo "... swig/AsmJitPYTHON_wrap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

